// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilaryuaxosmyieemyuak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYXJ5dWF4b3NteWllZW15dWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDk5NTMsImV4cCI6MjA3ODkyNTk1M30.Yzcswupb5d0ypon4sq2_UZpw6tKpwXS8WZPsOTGRPgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});